### ISSUE TITLE
Typo in the about

### ISSUE THREAD

**Issue by benedekrozemberczki** [cthoyt/chembl-downloader#1]
Hi Charlie,

There is a typo in the about.

"Write reproducible code for getting and processing ChEBML"

Bests,

Benedek

**Comment by cthoyt** [comment]
If I’m ever kidnapped, I’ll consistently spell ChEMBL correctly so everyone knows

**Comment by cthoyt** [comment]
Thanks for pointing this out!

**Comment by benedekrozemberczki** [comment]
Please do not get kidnapped. The community needs you.
