### ISSUE TITLE
Possibility to add custom dump location for downloader?

### ISSUE THREAD

**Issue by YojanaGadiya** [cthoyt/chembl-downloader#14]
@cthoyt I am aware that the ChEMBL gets downloaded at `~/.data/chembl` directory, but is it possible to pass a custom location or path?

If not, something you see could be added in future versions?

Regards,
Yojana Gadiya

**Comment by cthoyt** [comment]
Is https://github.com/cthoyt/chembl-downloader?tab=readme-ov-file#store-in-a-different-place insufficient?

**Comment by cthoyt** [comment]
you can also configure this deeper directly with pystow

**Comment by YojanaGadiya** [comment]
Oh thanks for the fast response. testing it now.. get back to you in a bit.
