### ISSUE TITLE
Repo status

### ISSUE THREAD

**Issue by YojanaGadiya** [cthoyt/chembl-downloader#4]
Dear @cthoyt,

I know that you have multiple responsibilities, but I was wondering if the current repo is in working condition or if is it a legacy repo which worked with a specific version of ChEMBL? It would be great if you could add a batch on the repo for the same.

Thank You.

**Comment by cthoyt** [comment]
This should work independently of the chembl version chosen (unless there were major changes to the file format, but at least the last 5 or so versions work as far as I know)

Was this not clear from the readme? How can that be improved?

**Comment by YojanaGadiya** [comment]
Hey, it did seem clear, but from past experiences, no one would reply/maintain even though such repos existed. 

I rather suggest having some guidelines for requesting an issue and also having a segment in the README on which versions of ChEMBL the downloader was tested. It gives an idea of how much function it is.

**Comment by cthoyt** [comment]
I’ll add a contributing document. Most of my repos are from a cookie cutter that has that automatically so this was an oversight. 

Would be happy to accept a PR with a table in the readme showing what versions you tested it on

**Comment by YojanaGadiya** [comment]
I would just be working on the latest one (31), but since it seems to be working for the past 5 versions as well.. I can test it quickly and send you the PR :)
